services:
  db_prod:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${BLUEPRINT_DB_PORT_PROD}:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  db_dev:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${BLUEPRINT_DB_PORT_DEV}:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  db_test:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${BLUEPRINT_DB_PORT_TEST}:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db_prod
      - db_dev
      - db_test

volumes:
  pgdata_prod:
  pgdata_dev:
  pgdata_test:

